apiVersion: v1
kind: ReplicationController
metadata:
  name: stickyip
  labels: 
    name: stickyip
    role: test
spec:
  replicas: 10
  selector:
    name: stickyip
    role: test
  template:
    metadata:
      name: stickyip
      labels:
        name: stickyip
        role: test
    spec:
      containers:
      - name: stickyip
        image: quay.io/lineberty/stickyiptest:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.01
            memory: 60Mi
---     
apiVersion: v1
kind: Service
metadata:
  name: stickyip
  labels: 
    name: stickyip
    role: test
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: stickyip
    role: test